name: Build & Deploy Flutter Web

on:
  push:
    branches:
      - main   # شغّل الـ Workflow عند أي دفع على فرع main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ اسحب الكود
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ ثبّت Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.3' # أو نسختك الحالية

      # 3️⃣ جلب الحزم
      - name: Install dependencies
        run: flutter pub get

      # 4️⃣ بناء نسخة الويب
      - name: Build Flutter Web
        run: flutter build web --release

      # 5️⃣ نشر على GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
